version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package -DskipTests

  build_and_push_docker_image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-dockerhub-username/your-app-name:$CIRCLE_SHA1 .
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push your-dockerhub-username/your-app-name:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build_and_push_docker_image:
          requires:
            - build
